import turtle
wn = turtle.Screen()
turtle.forward(60)
turtle.right(60)
turtle.forward(60)
turtle.right(60)
turtle.forward(60)
turtle.right(60)
turtle.forward(60)
turtle.right(60)
turtle.forward(60)
turtle.right(60)
turtle.forward(60)
wn.mainloop()