import turtle
wn = turtle.Screen()
turtle.penup()
turtle.setposition(0,-200)
turtle.pendown()
turtle.pencolor("blue")
turtle.left(90)
turtle.forward(536)
turtle.right(150)
turtle.forward(620)
turtle.right(120)
turtle.forward(310)

turtle.penup()
turtle.setposition(100,-50)
turtle.pendown()
turtle.pencolor("purple")
turtle.circle(50)
wn.mainloop()
